---
title: "ENVS-193DS_homework-03"
author: "Isaac Miller"
date: "2026-03-05"
format: 
  html:
    toc: true # use this to display a table of contents
---

# Set Up

[Link to my GitHub Repository](https://isaacmiller1113.github.io/ENVS-193DS_homework-03/code/ENVS-193DS_homework-03.html)

```{r}
#| label: set up chunk 
#| message: false

# Load in packages
library(tidyverse)     # general use
library(here)          # managing file paths relative to project root
library(janitor)       # cleaning data frames
library(readxl)        # importing data from excel files (.xls or .xlsx)
library(ggeffects)     # generating model predictions
library(gtsummary)     # generating summary tables for models
library(MuMIn)         # model selection and model inference
library(broom.helpers) # tidying and labeling model outputs

# Read in data objects
salinity <- read_csv(here("data", "salinity-pickleweed.csv")) |> 
  clean_names() # Store salinity data
  


```

# Problem 1. Slough soil salinity

You are working at a restoration site where you are managing planting of California pickleweed (Salicornia virginica) along a brackish slough (i.e. there is a mixture of fresh water and salt water).

You decide to measure plant growth for individual pickleweed plants by plucking an individual out of the ground and measuring the biomass (in g). You also measure soil salinity (as electrical conductivity in units of millisiemens per centimeter, or mS/cm) at the location in which the individual was growing. Admittedly, this isn’t a perfect study, but it’s what you can do with the time and resources you have!

## a. An appropriate test

The two appropriate tests are a Pearson's r correlation and linear regression. Pearson’s correlation ($r$) quantifies the strength and direction of the linear relationship between soil salinity and biomass as a single value between -1 and 1. In contrast, a linear regression models biomass as a functional response to the salinity predictor, allowing us to estimate the specific rate of change and predict biomass values.

The two appropriate tests are Pearson’s correlation and simple linear regression. Pearson’s correlation ($r$) is used to determine the strength and direction of the linear relationship between the two continuous variables: soil salinity (mS/cm) and California pickleweed biomass (g). While correlation provides a single unitless measure of how closely the points cluster around a line, simple linear regression models the response variable (biomass) as a function of the predictor variable (salinity), allowing us to quantify the specific effect size—how many grams of biomass are lost or gained for every 1 mS/cm increase in salinity.

: describes a linear relationship between a response variable and a predictor variable(s). beffore model: linear relationship and independent errors, after model: homoscedasticity (constant variance) and normally distributed error













